export const cardDetails = [
  {
    title: "Total Students Enrolled",
    number: "253,490",
    btnBg: "blue.600",
    cardBackground: "blue.100",
    titleColor: "blue.600",
    numberColor: "blue.600",
  },
  {
    title: "The Licensed schools",
    number: "1,134",
    btnBg: "green.600",
    cardBackground: "green.100",
    titleColor: "green.600",
    numberColor: "green.600",
  },
  {
    title: "Schools Awaiting License Renewal",
    titleSub: "Expiring within next 30 days",
    number: "42",
    cardBackground: "orange.100",
    btnBg: "orange.600",
    titleColor: "orange.600",
    numberColor: "orange.600",
  },
  {
    title: "Pending Transfer Requests",
    number: "176",
    cardBackground: "purple.100",
    btnBg: "purple.600",
    titleColor: "purple.600",
    numberColor: "purple.600",
  },
  {
    title: "Unlicensed Schools",
    number: "19",
    cardBackground: "red.100",
    btnBg: "red.600",
    titleColor: "red.600",
    numberColor: "red.600",
  },
  {
    title: "Exam-Eligible Students",
    number: "84,300",
    cardBackground: "cyan.100",
    btnBg: "cyan.600",
    titleColor: "cyan.600",
    numberColor: "cyan.600",
  },
];
